python_sources = [
    '__init__.py',
    'checking.py',
    'dim_base.py',
    'dim_float.py',
    'dimensions.py',
    'helpers.py',
    'legacy.py',
    'registry.py',
    'typing_aliases.py',
    'unit_table.py',
    'unit_tag.py'
]

py.install_sources(
    python_sources,
    subdir: 'fibomat/units'
)


